export const GET_PRODUCT_REQUEST= "GET_PRODUCT_REQUEST";
export const GET_PRODUCT_SUCCESS= "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_ERROR=  "GET_PRODUCT_ERROR";
export const GET_SINGLE_PRODUCT= "GET_SINGLE_PRODUCT";
export const GET_CART_DATA="GET_CART_DATA"
export const GET_CART_TOTAL_QUANTITY="GET_CART_TOTAL_QUANTITY"
export const GET_CART_AMOUNT="GET_CART_AMOUNT"
export const Post_ADDRESS ="POST_ADDRESS"

